
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author autologon
 */
public class Ui extends javax.swing.JFrame {
int somatorio=0;
  
    public Ui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Ocular = new javax.swing.JLabel();
        Motora = new javax.swing.JLabel();
        Verbal = new javax.swing.JLabel();
        CX01 = new javax.swing.JCheckBox();
        CX02 = new javax.swing.JCheckBox();
        CX03 = new javax.swing.JCheckBox();
        CX04 = new javax.swing.JCheckBox();
        CXM1 = new javax.swing.JCheckBox();
        CXM2 = new javax.swing.JCheckBox();
        CXM3 = new javax.swing.JCheckBox();
        CXM4 = new javax.swing.JCheckBox();
        CXM5 = new javax.swing.JCheckBox();
        CXV1 = new javax.swing.JCheckBox();
        CXV2 = new javax.swing.JCheckBox();
        CXV3 = new javax.swing.JCheckBox();
        CXV4 = new javax.swing.JCheckBox();
        CXV5 = new javax.swing.JCheckBox();
        CXV6 = new javax.swing.JCheckBox();
        Consultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela de coma Glasgow", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        Ocular.setText("Ocular");

        Motora.setText("Motora");

        Verbal.setText("Verbal");

        CX01.setText("1");
        CX01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CX01ActionPerformed(evt);
            }
        });

        CX02.setText("2");
        CX02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CX02ActionPerformed(evt);
            }
        });

        CX03.setText("3");
        CX03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CX03ActionPerformed(evt);
            }
        });

        CX04.setText("4");
        CX04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CX04ActionPerformed(evt);
            }
        });

        CXM1.setText("1");
        CXM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CXM1ActionPerformed(evt);
            }
        });

        CXM2.setText("2");
        CXM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CXM2ActionPerformed(evt);
            }
        });

        CXM3.setText("3");
        CXM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CXM3ActionPerformed(evt);
            }
        });

        CXM4.setText("4");
        CXM4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CXM4ActionPerformed(evt);
            }
        });

        CXM5.setText("5");
        CXM5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CXM5ActionPerformed(evt);
            }
        });

        CXV1.setText("1");
        CXV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CXV1ActionPerformed(evt);
            }
        });

        CXV2.setText("2");
        CXV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CXV2ActionPerformed(evt);
            }
        });

        CXV3.setText("3");
        CXV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CXV3ActionPerformed(evt);
            }
        });

        CXV4.setText("4");
        CXV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CXV4ActionPerformed(evt);
            }
        });

        CXV5.setText("5");
        CXV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CXV5ActionPerformed(evt);
            }
        });

        CXV6.setText("6");
        CXV6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CXV6ActionPerformed(evt);
            }
        });

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ocular)
                    .addComponent(Motora)
                    .addComponent(Verbal))
                .addGap(44, 44, 44)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(CX01)
                        .addGap(18, 18, 18)
                        .addComponent(CX02)
                        .addGap(18, 18, 18)
                        .addComponent(CX03)
                        .addGap(18, 18, 18)
                        .addComponent(CX04))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(CXM1)
                                .addGap(18, 18, 18)
                                .addComponent(CXM2)
                                .addGap(18, 18, 18)
                                .addComponent(CXM3)
                                .addGap(18, 18, 18)
                                .addComponent(CXM4))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(CXV1)
                                .addGap(18, 18, 18)
                                .addComponent(CXV2)
                                .addGap(18, 18, 18)
                                .addComponent(CXV3)
                                .addGap(18, 18, 18)
                                .addComponent(CXV4)))
                        .addGap(28, 28, 28)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(CXV5)
                                .addGap(30, 30, 30)
                                .addComponent(CXV6))
                            .addComponent(CXM5))))
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Consultar)
                .addGap(43, 43, 43))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ocular)
                    .addComponent(CX01)
                    .addComponent(CX02)
                    .addComponent(CX03)
                    .addComponent(CX04))
                .addGap(14, 14, 14)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Motora)
                    .addComponent(CXM1)
                    .addComponent(CXM2)
                    .addComponent(CXM3)
                    .addComponent(CXM4)
                    .addComponent(CXM5))
                .addGap(21, 21, 21)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Verbal)
                    .addComponent(CXV1)
                    .addComponent(CXV2)
                    .addComponent(CXV3)
                    .addComponent(CXV4)
                    .addComponent(CXV5)
                    .addComponent(CXV6))
                .addGap(11, 11, 11)
                .addComponent(Consultar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        switch (somatorio){
            case 3:
                JOptionPane.showMessageDialog(null, "O paciente está em coma profundo, com 85% de probabilidade de morte e em estado vegetativo.\n "
                + "Classificação do Trauma cranioencefálico (ATLS, 2005):Grave, com necessidade de intubação imediata.", "Resultado", JOptionPane.WARNING_MESSAGE);
                break;
            case 4:
            case 5:
            case 6:
                JOptionPane.showMessageDialog(null, "O paciente está em coma profundo! \n "
                    + "Classificação do Trauma cranioencefálico (ATLS, 2005):Grave, com necessidade de intubação imediata.", "Resultado", JOptionPane.WARNING_MESSAGE);
                break;
            case 7:
            case 8:
                JOptionPane.showMessageDialog(null, "O paciente está em coma intermediário!\n "
                    + "Classificação do Trauma cranioencefálico (ATLS, 2005):Grave, com necessidade de intubação imediata.", "Resultado", JOptionPane.WARNING_MESSAGE);
                break;
            case 9:
            case 10:
                JOptionPane.showMessageDialog(null, "O paciente está em coma intermediário!\n "
                    + "Classificação do Trauma cranioencefálico (ATLS, 2005):Moderado.", "Resultado", JOptionPane.WARNING_MESSAGE);
                break;
            case 11:
            case 12:
                JOptionPane.showMessageDialog(null, "O paciente está em coma superficial!\n "
                    + "Classificação do Trauma cranioencefálico (ATLS, 2005):Moderado.", "Resultado", JOptionPane.WARNING_MESSAGE);
                break;
            case 13:
            case 14:
                JOptionPane.showMessageDialog(null, "O paciente está em coma superficial!\n "
                    + "Classificação do Trauma cranioencefálico (ATLS, 2005):Leve.", "Resultado", JOptionPane.WARNING_MESSAGE);
                break;
            case 15:
                JOptionPane.showMessageDialog(null, "Normalidade!\n "
                    + "Classificação do Trauma cranioencefálico (ATLS, 2005):Leve.", "Resultado", JOptionPane.WARNING_MESSAGE);
                break;
            default: 
                JOptionPane.showMessageDialog(null, "Resultado inválido!\n ", "Resultado", JOptionPane.WARNING_MESSAGE);
                break;
        }
    
    }                                         

    private void CX01ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        CX02.setSelected (false);
        CX03.setSelected (false);
        CX04.setSelected (false);
        somatorio=1;
    }                                    

    private void CX02ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
         CX01.setSelected (false);
        CX03.setSelected (false);
        CX04.setSelected (false);
        somatorio=2;
    }                                    

    private void CX03ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        CX01.setSelected (false);
        CX02.setSelected (false);
        CX04.setSelected (false);
        somatorio=3;
    }                                    

    private void CX04ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
         CX01.setSelected (false);
        CX02.setSelected (false);
        CX03.setSelected (false);
        somatorio=4;
    }                                    

    private void CXM1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        CXM2.setSelected (false);
        CXM3.setSelected (false);
        CXM4.setSelected (false);
        CXM5.setSelected (false);
        somatorio +=1;
    }                                    

    private void CXM2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        CXM1.setSelected (false);
        CXM3.setSelected (false);
        CXM4.setSelected (false);
        CXM5.setSelected (false);
        somatorio +=2;
    }                                    

    private void CXM3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        CXM1.setSelected (false);
        CXM2.setSelected (false);
        CXM4.setSelected (false);
        CXM5.setSelected (false);
        somatorio +=3;
    }                                    

    private void CXM4ActionPerformed(java.awt.event.ActionEvent evt) {                                     
 
        CXM1.setSelected (false);
        CXM2.setSelected (false);
        CXM3.setSelected (false);
        CXM5.setSelected (false);
        somatorio +=4;
    }                                    

    private void CXM5ActionPerformed(java.awt.event.ActionEvent evt) {                                     
     
        CXM1.setSelected (false);
        CXM2.setSelected (false);
        CXM3.setSelected (false);
        CXM4.setSelected (false);
        somatorio +=5;
    }                                    

    private void CXV1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        
         CXV2.setSelected (false);
        CXV3.setSelected (false);
        CXV4.setSelected (false);
        CXV5.setSelected (false);
        CXV6.setSelected (false);
        somatorio +=1;
    }                                    

    private void CXV2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
     
        CXV1.setSelected (false);
        CXV3.setSelected (false);
        CXV4.setSelected (false);
        CXV5.setSelected (false);
        CXV6.setSelected (false);
        somatorio +=2;
        
    }                                    

    private void CXV3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        
         CXV1.setSelected (false);
        CXV2.setSelected (false);
        CXV4.setSelected (false);
        CXV5.setSelected (false);
        CXV6.setSelected (false);
        somatorio +=3;
    }                                    

    private void CXV4ActionPerformed(java.awt.event.ActionEvent evt) {                                     
       
         CXV1.setSelected (false);
        CXV2.setSelected (false);
        CXV3.setSelected (false);
        CXV5.setSelected (false);
        CXV6.setSelected (false);
        somatorio +=4;
    }                                    

    private void CXV5ActionPerformed(java.awt.event.ActionEvent evt) {                                     
       
        CXV1.setSelected (false);
        CXV2.setSelected (false);
        CXV3.setSelected (false);
        CXV5.setSelected (false);
        CXV6.setSelected (false);
        somatorio +=5;
    }                                    

    private void CXV6ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        
        CXV1.setSelected (false);
        CXV2.setSelected (false);
        CXV3.setSelected (false);
        CXV4.setSelected (false);
        CXV5.setSelected (false);
        somatorio +=6;
    }                                    

    
    public static void main(String args[]) {
     
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox CX01;
    private javax.swing.JCheckBox CX02;
    private javax.swing.JCheckBox CX03;
    private javax.swing.JCheckBox CX04;
    private javax.swing.JCheckBox CXM1;
    private javax.swing.JCheckBox CXM2;
    private javax.swing.JCheckBox CXM3;
    private javax.swing.JCheckBox CXM4;
    private javax.swing.JCheckBox CXM5;
    private javax.swing.JCheckBox CXV1;
    private javax.swing.JCheckBox CXV2;
    private javax.swing.JCheckBox CXV3;
    private javax.swing.JCheckBox CXV4;
    private javax.swing.JCheckBox CXV5;
    private javax.swing.JCheckBox CXV6;
    private javax.swing.JButton Consultar;
    private javax.swing.JLabel Motora;
    private javax.swing.JLabel Ocular;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel Verbal;
                       
}
